[options]

; =========================
; DATABASE
; =========================
db_host = False
db_port = False
db_user = odoo
db_password =
list_db = True
dbfilter = .*

; =========================
; SERVER
; =========================
xmlrpc_port = 8069
longpolling_port = 8072
proxy_mode = True

; =========================
; SECURITY
; =========================
admin_passwd = $pbkdf2-sha512$600000$4XyvFaK01hqDsHZujZFSqg$QToY4fBczZzZSsEWfVh.jO7wduE1tIs5EldmDM5aSaNXF.WV0qftqbcUV3Bel5ezKHGi056DXpnd/wR.rfXwCQ

; =========================
; ADDONS PATH (CRITICAL)
; =========================
addons_path = /home/odoo/odoo18/odoo/addons,/home/odoo/.local/share/Odoo/addons/18.0,/home/odoo/odoo18/addons,/home/odoo/odoo18/enterprise,/home/odoo/odoo18/custom_addons

; =========================
; DATA & LOGS
; =========================
data_dir = /home/odoo/.local/share/Odoo

; IMPORTANT: un seul logfile (pas de doublon)
logfile = /home/odoo/odoo18/odoo.log

; Mets debug pour tracer l’origine du message "compte client"
log_level = debug

; Trace mieux : HTTP + Models + Fields + SQL + Addons
log_handler = :DEBUG,odoo.http:DEBUG,odoo.models:DEBUG,odoo.fields:DEBUG,odoo.sql_db:DEBUG,odoo.addons:DEBUG

; =========================
; PERFORMANCE
; =========================
workers = 2
max_cron_threads = 1
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
limit_time_cpu = 120
limit_time_real = 240

; =========================
; PDF
; =========================
wkhtmltopdf_path = /usr/local/bin/wkhtmltopdf
root@ubuntu:~#